<Project Sdk="Microsoft.NET.Sdk.Worker"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup><ItemGroup><ProjectReference Include="../OrderFlow.Contracts/OrderFlow.Contracts.csproj" /><PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" /></ItemGroup></Project>
