<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../OrderFlow.Application/OrderFlow.Application.csproj" /><ProjectReference Include="../OrderFlow.Domain/OrderFlow.Domain.csproj" /><ProjectReference Include="../OrderFlow.Contracts/OrderFlow.Contracts.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12"><PrivateAssets>all</PrivateAssets></PackageReference><PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" /><PackageReference Include="Grpc.Net.ClientFactory" Version="2.66.0" /><PackageReference Include="RabbitMQ.Client" Version="6.8.1" /></ItemGroup></Project>
