<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../OrderFlow.Application/OrderFlow.Application.csproj" /><ProjectReference Include="../OrderFlow.Domain/OrderFlow.Domain.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" /></ItemGroup></Project>
